// <auto-generated />
namespace scoutfjallstugan.se.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AttendId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AttendId));
        
        string IMigrationMetadata.Id
        {
            get { return "201312101250397_AttendId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
